baseURL = 'http://example.org/'
languageCode = 'en-gb'
title = 'FYP22002@HKUCS'
theme = "ananke"
[params]
  date_format = "Mon 02-Jan-2006 15:04:05 -07:00"
  background_color_class = "bg-navy"
[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/vicw0ng-hk"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
