baseURL = "https://vicw0ng-hk.github.io/feul/"
languageCode = 'en-gb'
title = 'FYP22002@HKUCS'
theme = "ananke"
SectionPagesMenu = "main"
Paginate = 10
[params]
  date_format = "Mon 02-Jan-2006 15:04:05 -07:00"
  background_color_class = "bg-navy"
  favicon = "images/brain.png"
  custom_css = ["style.css"]
[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/vicw0ng-hk/"
[[params.ananke_socials]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/vicw0ng/"
  share = false
[markup.goldmark.renderer]
  unsafe = true
